[package]
name = "anaso_algorithm"
description = "The recommendation algorithm for Ana.so"
version = "0.1.2"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Brandon Dyer <brandono@ana.so>"]

[dependencies]
